// svelte-app/src/liker/liker.svelte
<!-- liker buttons -->
<script>
  export let like = 0;
  export let dislike = 0;
  function onLike() {
    like++;
  }
  function onDislike() {
    dislike++;
  }
</script>

<div>
  <button on:click={onLike}>Like</button>
  <button on:click={onDislike}>Dislike</button>
  <p>{like} Likes - {dislike} Dislikes</p>
</div>

// angular-app/src/app/liker/liker.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-liker',
  template: `
    <div>
      <button id="like" (click)="like()">Like</button>
      <button id="dislike" (click)="dislike()">Dislike</button>
      <p>{{ likes }} Likes - {{ dislikes }} Dislikes</p>
    </div>
  `,
})
export class LikerComponent {
  likes = 0;
  dislikes = 0;

  like() {
    this.likes++;
  }

  dislike() {
    this.dislikes++;
  }
}
